### ISSUE TITLE
Ignoring data extracts -- not working?

### ISSUE THREAD

**Issue by jrpepin** [roseamw/ATUSGenderSequenceAnalysis#2]
I tried to update the .do files with functioning/shareable file paths. But, I'm getting an error trying to make a commit about the file size exceeding GitHub's limits now that I have the files pulling from the data extracts folder. 

I'm guessing this is because the data files in the extract folders are still picking up one of the file types. The files in this folder include: .dat .dta and .do 

I organized the data extracts  in 4 sub-folders in the Data extracts folder. Could that be the problem?

@sarahflood : Can you check on this?

**Comment by jrpepin** [comment]
![image](https://user-images.githubusercontent.com/31118173/29490285-c247b2ca-8505-11e7-9a2f-f21f6b2065b9.png)
This is the error I'm getting, FYI.

**Comment by sarahflood** [comment]
I think we should ignore .dta files. I've made that change to .gitignore and pushed it so you should be able to pull in this change and try to commit your changes again.

**Comment by jrpepin** [comment]
As far as I can tell, that must have worked! Thanks @sarahflood!!
