### ISSUE TITLE
Married people without a spouse in the household.

### ISSUE THREAD

**Issue by sarahflood** [roseamw/ATUSGenderSequenceAnalysis#7]
Because marital status is asked at the time of the CPS interview, there can be a mismatch between a respondent's marital status and the actual presence of a spouse in the household. In 2016, there are 190 respondents who fall into this marital status-spouse presence category. I propose that we code them as separated in the most detailed marital status variable and put them in the divorced/separated/widowed category of the more general marital status variable. Thoughts?

.  tab marst spousepres if marstat==0

                      | Spouse or
                      | unmarried
                      | partner in
                      | household
       Marital status | No spouse |     Total
----------------------+-----------+----------
Married - spouse pres |        28 |        28 
Married - spouse abse |       162 |       162 
----------------------+-----------+----------
                Total |       190 |       190

**Comment by jrpepin** [comment]
This sounds reasonable to me!  I'll defer to your expertise on this.

**Comment by sarahflood** [comment]
Done. We can always revisit this decision.
