### ISSUE TITLE
random sample?

### ISSUE THREAD

**Issue by sarahflood** [roseamw/ATUSGenderSequenceAnalysis#8]
Do we need to take a random sample of 500 cases from 2016? This is commented out in Joanna's code so I assume not, but want to confirm.

**Comment by jrpepin** [comment]
This is Rose's call. I used the random sample because the sequence analyses I used took forever to run so a smaller sample helped. I left the code in case Rose also wanted needed to do that.

**Comment by sarahflood** [comment]
Thanks, @jrpepin. Considering this a non-issue unless it comes up again.
